development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: first_app_dev
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: first_app_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: first_app
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST